---
title: "Spring Semester Goals"
author: Shama Hasan
date: 2026-02-27
categories: [goals, daily-entries]
description: "Spring 2026 Goals"
image: ""
---

# Overview

Spring 2026 goals

## Goals

### Writing and Manuscripts 

1. Start writing introduction section of apicomplexa paper
2. Outline and plan for honors thesis
3. Frequent lab notebook entries detailing my independent and lab research

### Analysis and Benchwork

1. Continue with BAT analysis and gene alignments
2. Group / collaborative genome lab project
3. Develop microscope and lab procedure expertise 
4. Maintain and document ciliate cultures

### Funding

1. Submit Charles Center Summer Grant proposal

### Other

1. Set up digital notebook
2. Determine timeline for summer and senior year honors research
3. Lots of reading for summer/honors project (APICOMPLEXA!!)

### Planned Posts

- [ ] Updating my Notebook 
- [ ] Apicomplexan Genome Evolution 
- [ ] CLI Tutorial 
    - basic intro tutorial, index of commands, etc.
- [ ] Microscope image gallery 

# Primary Skill Building

- [ ] command line interface (CLI)
- [ ] wet lab procedures (cell cultures, PCR, etc.)
- [ ] writing and documentation 
